# Build AzureImageBuilder Pipeline
# Build All Azure Image Builder Pipielines - calls all PS1 after EntDesktop
trigger: none

pool:
  name: aib-ap

steps:
# PowerShell
# Run a PowerShell script on Linux, macOS, or Windows
- task: AzureFileCopy@4
  inputs:
    SourcePath: 'scripts/*'
    TargetPath: ''
    azureSubscription: 'WVD-Dev'
    Destination: 'AzureBlob'
    storage: 'aibdev'
    ContainerName: 'scripts'
- task: AzurePowerShell@5
  timeoutInMinutes: 360
  inputs:
    azureSubscription: 'WVD-Dev' #This is the devops service connection name
    ErrorActionPreference: 'Stop'
    FailOnStandardError: true
    ScriptType: 'FilePath'
    ScriptPath: './aibBulkDeploy.ps1'
    
    azurePowerShellVersion: 'LatestVersion'
  displayName: 'Run Azure Image Builder aibBulkDeploy'



  
